### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jimschubert** [soldierq/QLicense#1]
Saw this on code project, but this repo doesn't have a license file. Is this also to be CPOL?

**Comment by soldierq** [comment]
Just new to GitHub, not sure about the license file you mentioned. It is CPOL as well. Shall I put some file here as well?

**Comment by jimschubert** [comment]
I would add a license file to indicate that this is open source. Not everyone will have found it through Codeplex. Oddly, plenty of people publicly post proprietary code without licenses; when people assume it's open source because the code is on github, legal battles may ensue.

Here's more info on applying licenses: https://help.github.com/articles/open-source-licensing/. It's not really a github only thing, they just make it really easy to start with a license and advocate for including licenses. I'd use a license in BitBucket or any other public code hosting platform.

The main reason I ask is because some companies don't allow open source code to be used unless there are clear licensing terms included with the source.

If you'd like, I can add the license and open a pull request.

**Comment by soldierq** [comment]
Thanks for your suggestion. I'd like to look into the license stuff myself and do some homework for it.

**Comment by soldierq** [comment]
MIT license file added, close this issue.

Thanks for the reminder.
