### ISSUE TITLE
LicenseSign.pfx in DemoActionTool project is not exist

### ISSUE THREAD

**Issue by ZhangDonglin12** [soldierq/QLicense#10]
Hello soldierq，
 when i check out your code ,i found the LicenseSign.pfx file can't find when i build the project?
Can you help to fix that?Thanks a lot.

**Comment by michaelmsonne** [comment]
You need to create a keypair (.pfx and .cer) by yourself :)

**Comment by ZhangDonglin12** [comment]
How could i creat a keypair ?,Sorry ,I have no idea about the license file in C# ,could you provide some reference books for me?Thanks a lot

**Comment by michaelmsonne** [comment]
A good start is here, i had used that to create a self-signed certificate, then exported the "public" ket from Windows cert store as .cer :)

https://www.petri.com/create-self-signed-certificate-using-powershell

**Comment by ZhangDonglin12** [comment]
Thanks for your help.

**Comment by michaelmsonne** [comment]
No problem ;)
