### ISSUE TITLE
hOW CAN I CREATE / GET DemoActivationTool.LicenseSign.pfx FILE?

### ISSUE THREAD

**Issue by AmerQwaider** [soldierq/QLicense#12]
hOW CAN I CREATE / GET DemoActivationTool.LicenseSign.pfx FILE?

**Comment by luifertorres** [comment]
Here are the steps to create the KeyPair and exported public key file:
https://www.codeproject.com/Articles/996001/A-Ready-To-Use-Software-Licensing-Solution-in-Csha#premain925383
